
/* v22 STABILIZATION UI — current-car information and compact score/wanted HUD. */
(function(){
'use strict';if(!window.GameSystems)return;
const clamp=(v,a,b)=>v<a?a:v>b?b:v;
(function(){let ctx=null,root=null,canvas=null,text=null,open=false,tick=0;
 function ensure(){if(root)return;const st=document.createElement('style');st.textContent='#carInfoV22{position:absolute;right:18px;top:126px;z-index:125;width:min(390px,calc(100vw - 36px));display:none;pointer-events:auto;border:1px solid rgba(32,227,255,.75);border-radius:15px;background:linear-gradient(145deg,rgba(5,11,20,.96),rgba(13,21,34,.94));box-shadow:0 16px 60px #000;color:#eaf5ff;padding:15px;font:800 11px/1.45 system-ui}#carInfoV22.on{display:block}#carInfoV22 h2{margin:0 0 7px;color:#20e3ff;letter-spacing:2px;font-size:17px}#carInfoV22 .meta{color:#9eb0c8;white-space:pre-line;margin-bottom:8px}#carInfoV22 canvas{width:100%;height:230px}#carInfoV22 button{float:right;background:none;border:1px solid #40516b;color:#fff;border-radius:7px;cursor:pointer}';document.head.appendChild(st);root=document.createElement('div');root.id='carInfoV22';root.innerHTML='<button>×</button><h2>CURRENT VEHICLE</h2><div class="meta"></div><canvas width="700" height="430"></canvas>';ctx.dom.ui.appendChild(root);root.querySelector('button').onclick=close;text=root.querySelector('.meta');canvas=root.querySelector('canvas');}
 function fleetHandlingRanges(){
   const bench=window.VEHICLE_BENCHMARKS&&window.VEHICLE_BENCHMARKS.cars||{},rows=[];
   for(const id of Object.keys(bench)){const h=ctx.engine.vehicleHandlingTelemetry?ctx.engine.vehicleHandlingTelemetry(id,true):null;if(h)rows.push(h);}
   const range=k=>{const a=rows.map(r=>Number(r[k])).filter(Number.isFinite);return{lo:Math.min(...a),hi:Math.max(...a)};};
   return{grip:range('gripMetric'),drift:range('driftMetric'),steer:range('steerMetric'),recovery:range('recoveryMetric')};
 }
 function normUp(v,r){return r&&r.hi>r.lo?clamp((v-r.lo)/(r.hi-r.lo),0,1):0;}
 function normTime(v,fast,slow){return Number.isFinite(v)&&slow>fast?clamp((slow-v)/(slow-fast),0,1):0;}
 function stats(){
   const t=ctx.vehicles.tune,p=GameSystems.api('progression'),up=GameSystems.api('vehicleUpgrades'),id=p&&p.currentVehicle?p.currentVehicle():ctx.vehicles.currentKey,
     entry=p&&p.entry?p.entry(id):null,preset=p&&p.presetOf?p.presetOf(id):'stock',protect=up&&up.state?up.state(id):{armor:0,proofTires:false},pt=ctx.engine.powertrain?ctx.engine.powertrain():{},
     pack=window.VEHICLE_BENCHMARKS||{},axis=pack.axis||{},bench=pack.cars&&pack.cars[id]||null,handling=ctx.engine.vehicleHandlingTelemetry?ctx.engine.vehicleHandlingTelemetry(id,true):null,ranges=fleetHandlingRanges();
   const n60=bench?normTime(bench.zeroTo60,axis.zeroTo60Fast,axis.zeroTo60Slow):0,has100=Number.isFinite(axis.zeroTo100Fast)&&Number.isFinite(axis.zeroTo100Slow)&&axis.zeroTo100Slow>axis.zeroTo100Fast,n100=bench&&has100&&Number.isFinite(bench.zeroTo100)?normTime(bench.zeroTo100,axis.zeroTo100Fast,axis.zeroTo100Slow):n60,
     accel=has100?n60*.65+n100*.35:n60,top=bench&&axis.topFast>axis.topSlow?clamp((bench.topSpeed-axis.topSlow)/(axis.topFast-axis.topSlow),0,1):0,
     durability=clamp(((pt.engineCondition||100)+(pt.transmissionCondition||100))/200*.65+(protect.armor||0)*.12,0,1);
   return{id,name:entry&&entry.displayName||t.name,preset,installed:t.installedHardware||[],ecu:t.extremeTune?'EXTREME':t.hardwareStage?('STAGE '+t.hardwareStage):'FACTORY',protection:protect,nitrousInstalled:!!pt.nitrousInstalled,forcedInduction:pt.forcedInduction||'na',bench,handling,
     values:[accel,top,handling?normUp(handling.gripMetric,ranges.grip):0,handling?normUp(handling.driftMetric,ranges.drift):0,handling?normUp(handling.steerMetric,ranges.steer):0,handling?normUp(handling.recoveryMetric,ranges.recovery):0,durability]};
 }
 function fmtBench(v){return Number.isFinite(v)?(+v).toFixed(2).replace(/\.00$/,''):'N/A';}
 function draw(){
   if(!open||!canvas)return;const d=stats(),g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,cx=w*.5,cy=h*.51,R=Math.min(w,h)*.36,labels=['ACCEL','TOP SPEED','GRIP','DRIFT','STEER','RECOVERY','DURABILITY'];
   g.clearRect(0,0,w,h);g.lineWidth=2;g.font='800 20px system-ui';g.textAlign='center';
   for(let ring=1;ring<=4;ring++){g.strokeStyle='rgba(70,102,135,'+(.12+ring*.035)+')';g.beginPath();for(let i=0;i<labels.length;i++){const a=-Math.PI/2+i*Math.PI*2/labels.length,x=cx+Math.cos(a)*R*ring/4,y=cy+Math.sin(a)*R*ring/4;i?g.lineTo(x,y):g.moveTo(x,y);}g.closePath();g.stroke();}
   g.fillStyle='rgba(32,227,255,.18)';g.strokeStyle='#20e3ff';g.shadowColor='#20e3ff';g.shadowBlur=12;g.beginPath();for(let i=0;i<labels.length;i++){const a=-Math.PI/2+i*Math.PI*2/labels.length,x=cx+Math.cos(a)*R*d.values[i],y=cy+Math.sin(a)*R*d.values[i];i?g.lineTo(x,y):g.moveTo(x,y);}g.closePath();g.fill();g.stroke();g.shadowBlur=0;
   for(let i=0;i<labels.length;i++){const a=-Math.PI/2+i*Math.PI*2/labels.length;g.fillStyle='#cdd9e9';g.fillText(labels[i],cx+Math.cos(a)*(R+42),cy+Math.sin(a)*(R+28)+7);}
   const b=d.bench||{},src=String(b.source||'unbenchmarked').toUpperCase().replace(/-/g,' '),benchLine=d.bench?('STOCK BENCH 0-60 '+fmtBench(b.zeroTo60)+'s · 0-100 '+fmtBench(b.zeroTo100)+'s · TOP '+fmtBench(b.topSpeed)+' QA'):'STOCK BENCH unavailable';
   text.textContent=d.name+' · '+d.preset.toUpperCase()+'\n'+benchLine+'\nSOURCE '+src+' · GRAPH SCALE = VALID V32 MEASURED RUNS\nECU '+d.ecu+' · HARDWARE '+(d.installed.length?d.installed.join(', '):'STOCK')+'\nNITRO '+(d.nitrousInstalled?'INSTALLED':'NOT INSTALLED')+' · TURBO '+(d.forcedInduction==='turbo'?'INSTALLED':d.forcedInduction==='supercharger'?'SUPERCHARGED':'NATURALLY ASPIRATED')+'\nARMOUR TIER '+(d.protection.armor||0)+' · PUNCTURE-PROOF '+(d.protection.proofTires?'YES':'NO');
 }
 function openPanel(){if(ctx.player.onFoot||ctx.player.inAircraft)return false;ensure();open=true;root.classList.add('on');draw();return true;}function close(){open=false;if(root)root.classList.remove('on');}
 GameSystems.register({id:'carInfo',order:108,alwaysUpdate:true,init(c){ctx=c;ensure();},onKey(k){if(k==='i'&&!ctx.player.onFoot&&!ctx.player.inAircraft){open?close():openPanel();return true;}if(open&&k==='escape'){close();return true;}return open;},update(dt){if(open&&(ctx.player.onFoot||ctx.player.inAircraft)){close();return;}if(open&&(tick-=dt)<=0){tick=.2;draw();}},api:{open:openPanel,close,toggle(){return open?close():openPanel();},get open(){return open;}}});
})();
(function(){let ctx=null,root=null,score=null,cash=null,streak=null,stars=[],lastScore=-1,lastWanted=-1;
 function ensure(){if(root)return;const oldScore=document.getElementById('cash'),oldStars=document.getElementById('stars'),st=document.createElement('style');st.textContent='#scoreWantedV22{position:absolute;left:18px;top:16px;z-index:24;min-width:204px;padding:10px 13px;border:1px solid rgba(32,227,255,.38);border-radius:12px;background:linear-gradient(135deg,rgba(5,9,17,.83),rgba(17,8,28,.76));box-shadow:0 8px 30px rgba(0,0,0,.42),inset 0 0 22px rgba(32,227,255,.035);font:900 12px/1.15 system-ui;color:#fff;pointer-events:none}#scoreWantedV22 .top{display:flex;justify-content:space-between;gap:16px;align-items:baseline}#scoreWantedV22 .score{font-size:19px;letter-spacing:1px;color:#fff}#scoreWantedV22 .score.bump{animation:scoreBump .22s ease-out}#scoreWantedV22 .money{color:#3bff8b}#scoreWantedV22 .wanted{margin-top:6px;display:flex;gap:4px}#scoreWantedV22 .star{font-size:18px;color:#263348;text-shadow:none;transition:.25s}#scoreWantedV22 .star.on{color:#ffd23f;text-shadow:0 0 7px #ffd23f,0 0 16px rgba(255,210,63,.75)}#scoreWantedV22 .star.gain{animation:starGain .38s ease-out}#scoreWantedV22 .star.loss{animation:starLoss .45s ease-out}#scoreWantedV22 .streak{margin-left:auto;color:#ff7abf;letter-spacing:.8px;display:none}#scoreWantedV22 .streak.on{display:inline}@keyframes scoreBump{50%{transform:scale(1.13);color:#20e3ff}}@keyframes starGain{50%{transform:scale(1.45)}}@keyframes starLoss{35%{opacity:.15;transform:rotate(-18deg)}}#cash,#stars{display:none!important}';document.head.appendChild(st);root=document.createElement('div');root.id='scoreWantedV22';root.innerHTML='<div class="top"><span class="score">0</span><span class="money">$0</span></div><div class="wanted"></div><span class="streak"></span>';ctx.dom.ui.appendChild(root);score=root.querySelector('.score');cash=root.querySelector('.money');streak=root.querySelector('.streak');const w=root.querySelector('.wanted');for(let i=0;i<6;i++){const q=document.createElement('span');q.className='star';q.textContent='★';w.appendChild(q);stars.push(q);}if(oldScore)oldScore.style.display='none';if(oldStars)oldStars.style.display='none';}
 function paint(){ensure();const ss=ctx.engine.scoreStreakState?ctx.engine.scoreStreakState():{points:0,mult:1,timer:0},wallet=GameSystems.api('progression');if(ctx.stats.score!==lastScore){score.textContent=ctx.stats.score.toLocaleString();score.classList.remove('bump');void score.offsetWidth;score.classList.add('bump');lastScore=ctx.stats.score;}cash.textContent='$'+(wallet&&wallet.wallet?wallet.wallet():0).toLocaleString();if(ctx.stats.wanted!==lastWanted){for(let i=0;i<6;i++){const was=i<lastWanted,now=i<ctx.stats.wanted;stars[i].className='star'+(now?' on':'')+(now&&!was?' gain':was&&!now?' loss':'');}lastWanted=ctx.stats.wanted;}streak.textContent='STREAK '+Math.floor(ss.points).toLocaleString()+' · ×'+(+ss.mult||1).toFixed(1);streak.classList.toggle('on',ss.points>0);}
 GameSystems.register({id:'scoreHud',order:109,alwaysUpdate:true,init(c){ctx=c;ensure();},update:paint,api:{paint}});
})();
})();
